@echo off
echo Ejecutando el backend con H2...
set SPRING_DATASOURCE_URL=jdbc:h2:mem:bitacoradb
set SPRING_DATASOURCE_USERNAME=sa
set SPRING_DATASOURCE_PASSWORD=
set SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
set SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
set SPRING_H2_CONSOLE_ENABLED=true
set SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
set SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true
set SPRING_SQL_INIT_MODE=always

mvn spring-boot:run
