server:
  port: 8081

spring:
  # Configuración de Flyway para H2
  flyway:
    locations: classpath:db/migration,classpath:db/migration/dev
    out-of-order: true
    baseline-on-migrate: true

  # Deshabilitar carga de data.sql
  sql:
    init:
      mode: never

  # Configuración de H2
  datasource:
    url: jdbc:h2:mem:bitacoradb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # Configuración de H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
