server:
  port: 8080

spring:
  # Configuración de Flyway para H2
  flyway:
    locations: classpath:db/migration,classpath:db/migration/dev
    out-of-order: true
    baseline-on-migrate: true

  # Deshabilitar carga de data.sql
  sql:
    init:
      mode: never

  # Configuración de H2
  datasource:
    url: jdbc:h2:mem:bitacoradb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # Configuración de H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.web: DEBUG
    com.bitacora.infrastructure.config: DEBUG # Para logs de inicialización de datos

# Configuración para usar el nuevo sistema de datos configurables
# Para activar: --spring.profiles.active=dev,configurable-data-init,dev-data
#
# Ejemplo de variables de entorno para desarrollo:
# export ADMIN_PASSWORD="tu-password-admin-seguro"
# export SEMPER_PASSWORD="tu-password-semper-seguro"
